# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

setenv overlay_error "false"
# default values
setenv rootdev "/dev/mmcblk0p1"
setenv verbosity "1"
setenv console "both"
setenv bootlogo "false"
setenv rootfstype "ext4"
setenv docker_optimizations "on"
setenv earlycon "off"

echo "Boot script loaded from ${devtype} ${devnum}"

if test -e ${devtype} ${devnum} ${prefix}armbianEnv.txt; then
	echo "skip load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}armbianEnv.txt"
	#load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}armbianEnv.txt
	#env import -t ${ramdisk_addr_r} ${filesize}
fi

setenv bootargs 'rootfstype=ext4 root=/dev/mmcblk1p2 rw rootwait'
mmc list
fatload mmc 1:1 0x4b800000 dtb/synaptics/vs680-a0-evk.dtb
fatload mmc 1:1 0x04c80000 Image
booti 0x04c80000 - 0x4b800000


# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
# mkimage -C none -A arm -T script -d boot.cmd boot.scr
